Accelerometer
MissouriMRDT/BaseStation_Software pull request #353
Opened 2024-04-03 22:30 UTC by OcelotEmpire

### Things Added:
- overhaul of old ThreeDRover using react-three/fiber and react-three/drei libraries
- updated 3D models to match the current rover
- greatly reduced poly count to improve performance
- 3D models rotate in real time according to a "down" vector
- shadows to make the rotation more readable
- debug tools to apply rotations manually
- support for .gltf and .glb files, allowing materials and animations
### Things Still Needed:
- RoveComm packet called AccelerometerData containing 3 floats added to manifest
- maybe some error handling to make the console less cluttered

2024-04-04 00:55 UTC, wiidler commented on assets/Waypoints.json
try not to push new waypoints, we want to keep these, so reset this file to dev

2024-04-04 00:55 UTC, wiidler commented on assets/models/tex01.png
no

2024-04-04 00:57 UTC, wiidler commented on src/Core/components/Accelerometer.tsx
do we need debug panel on final merge to dev?

2024-04-04 00:59 UTC, wiidler requested changes
Address comments

2024-04-04 01:20 UTC, OcelotEmpire commented on src/Core/components/Accelerometer.tsx
no, but it can stay until the hardware is installed

2024-04-04 01:25 UTC, OcelotEmpire commented on assets/models/tex01.png
yes

2024-06-12 22:10 UTC, wiidler commented
Merged to https://github.com/MissouriMRDT/BaseStation_Software/pull/355

2024-06-12 22:10 UTC, closed without merging